services:
  humanizer:
    build: .
    container_name: humanizer-ethics-v3
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - OPENROUTER_API_KEY=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
    restart: unless-stopped
